import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1024},deviceScaleFactor:1});
const errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const base=process.env.QA_URL||'http://127.0.0.1:4381';
const pause=()=>page.waitForTimeout(350);
const pass=name=>{checks.push(name);console.log('PASS',name);};
const capture=async(options)=>{
  const dismiss=page.getByRole('button',{name:'Dismiss notification'});
  if(await dismiss.count())await dismiss.click();
  await page.mouse.move(500,0);await page.evaluate(()=>window.scrollTo(0,0));await pause();
  await page.screenshot(options);
};
try {
  await page.goto(base,{waitUntil:'networkidle'});
  await page.locator('.score-value').waitFor();
  assert.equal(await page.locator('.score-value').textContent(),'6.50');
  assert.match(await page.locator('.coverage-bar').innerText(),/71 of 79/);
  assert.equal(await page.locator('.leaflet-interactive').count(),79);pass('Source values, mapped coverage, and 79 county features');
  assert.ok(await page.getByRole('button',{name:'Open county profile'}).isVisible());
  const action=await page.getByRole('button',{name:'Open county profile'}).boundingBox(),inspector=await page.locator('.county-inspector').boundingBox();
  assert.ok(action.y+action.height<=inspector.y+inspector.height);pass('County action fully visible without inspector scrolling');
  await capture({path:'qa/overview-light.png'});
  const before=await page.locator('.leaflet-interactive[aria-label^="Twic East —"]').getAttribute('fill');
  await page.getByRole('button',{name:'Dark mode',exact:true}).click();await pause();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  assert.equal(await page.locator('.leaflet-interactive[aria-label^="Twic East —"]').getAttribute('fill'),before);
  await capture({path:'qa/overview-dark.png'});pass('Theme toggle retains severity colour and layout');
  await page.locator('.leaflet-interactive[aria-label^="Fangak —"]').focus();await page.keyboard.press('Enter');await pause();
  assert.equal(await page.locator('.inspector-heading h1').textContent(),'Fangak');pass('Keyboard map selection updates inspector');
  await page.getByRole('textbox',{name:'Search county'}).fill('Twic East');
  await page.locator('.search-results button').first().click();await pause();
  assert.equal(await page.locator('.inspector-heading h1').textContent(),'Twic East');pass('County search updates selected county');
  await page.getByLabel('State',{exact:true}).selectOption('Jonglei');
  await page.getByLabel('Band',{exact:true}).selectOption('B1');await pause();
  assert.ok(await page.locator('.selection-notice').isVisible());
  await page.getByRole('button',{name:'Table',exact:true}).click();
  const states=await page.locator('.county-table tbody tr td:nth-child(2)').allTextContents();
  assert.ok(states.length>0&&states.every(s=>s==='Jonglei'));pass('State and band filters update county table and map');
  const download=page.waitForEvent('download');await page.getByTitle('Download current filtered counties').click();
  const csv=await download;await csv.saveAs('qa/filtered-data.csv');
  assert.match(await fs.readFile('qa/filtered-data.csv','utf8'),/Jonglei/);pass('Filtered CSV download');
  await page.getByLabel('State',{exact:true}).selectOption('all');await page.getByLabel('Band',{exact:true}).selectOption('all');
  await page.getByRole('button',{name:'Map',exact:true}).click();
  await page.getByLabel('Map indicator',{exact:true}).selectOption('IPC_AFI_phase_severity');await pause();
  assert.match(await page.locator('.map-legend').textContent(),/Phase 5/);
  await page.getByLabel('Map indicator',{exact:true}).selectOption('band');pass('Indicator layer and phase legend switch together');
  await page.getByRole('button',{name:'Open county profile'}).click();await pause();
  assert.equal(await page.locator('.county-heading h1').textContent(),'Twic East County');
  assert.match(await page.locator('.comparison-summary strong').textContent(),/-0.25/);
  await capture({path:'qa/county-dark.png'});pass('County page and real-period comparison');
  await page.getByRole('button',{name:'Light mode',exact:true}).click();await pause();
  await capture({path:'qa/county-light.png'});
  await page.getByRole('tab',{name:'Indicator data'}).click();assert.equal(await page.locator('.indicator-card').count(),8);await page.getByRole('button',{name:'Indicator table',exact:true}).click();assert.equal(await page.locator('.indicator-data tbody tr').count(),8);
  await page.getByRole('tab',{name:'Notes & sources',exact:true}).click();assert.match(await page.locator('.notes-panel').textContent(),/Abyei/);pass('Indicator and source-note tabs');
  const briefWait=page.waitForEvent('download');await page.getByRole('button',{name:'Download county brief',exact:true}).click();const brief=await briefWait;assert.ok(brief.suggestedFilename().endsWith('.html'));pass('Printable county brief download');
  await page.getByLabel('Reporting period').selectOption('2025-12');await page.getByRole('tab',{name:'Overview',exact:true}).click();await pause();assert.equal(await page.locator('.score-value').textContent(),'—');pass('Partial-period missing county is not assigned a score');
  await page.getByLabel('Reporting period').selectOption('2025-10');await page.getByRole('button',{name:'Choose county',exact:true}).click();await page.getByRole('combobox',{name:'Search county or state'}).fill('Yei');await page.getByRole('option',{name:'Yei',exact:true}).click();await pause();
  assert.match(await page.locator('.data-message').textContent(),/Conflicting/);assert.equal(await page.locator('.score-value').textContent(),'—');
  await page.getByRole('tab',{name:'Indicator data'}).click();assert.equal(await page.getByLabel('Source submission').locator('option').count(),2);pass('Conflicting county/month records are exposed and not averaged');
  await page.getByRole('button',{name:'Choose county',exact:true}).click();await page.getByRole('combobox',{name:'Search county or state'}).fill('Twic East');await page.getByRole('option',{name:'Twic East',exact:true}).click();await page.getByLabel('Reporting period').selectOption('2025-11');await page.getByRole('tab',{name:'Overview',exact:true}).click();
  await page.getByRole('button',{name:'Publications',exact:true}).click();await pause();
  assert.equal((await page.request.get(base+'/publications/NAWG_September_2026.pptx')).status(),200);pass('Supplied PPT publication is downloadable');
  await page.getByRole('button',{name:'About & methodology',exact:true}).click();assert.match(await page.locator('.about-page').textContent(),/49 county\/month/);pass('Source methodology and quality audit');
  await page.getByRole('button',{name:'National overview',exact:true}).click();await page.setViewportSize({width:390,height:844});await pause();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
  await capture({path:'qa/mobile-overview.png',fullPage:true});
  await page.getByRole('button',{name:'Open county profile'}).click();await pause();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
  await capture({path:'qa/mobile-county.png',fullPage:true});pass('390px mobile overview and county layout without horizontal overflow');
  await page.setViewportSize({width:1024,height:900});await pause();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),1024);await page.screenshot({path:'qa/tablet-county.png'});pass('1024px tablet layout without horizontal overflow');
  await page.setViewportSize({width:1440,height:1024});await page.getByRole('button',{name:'National overview',exact:true}).click();await pause();
  const responseWait=page.waitForResponse(r=>r.url().includes('/api/data?refresh=1'),{timeout:60000});await page.locator('.sync-status').click();const response=await responseWait;assert.equal(response.status(),200);const refreshed=await response.json();assert.ok(Array.isArray(refreshed.rows));assert.ok(!refreshed.warning);pass('Live ActivityInfo refresh through server');
  const token=(await fs.readFile('.env.local','utf8')).split('=')[1].trim();
  assert.ok(!JSON.stringify(refreshed).includes(token));pass('Credential is absent from browser API data');
  assert.deepEqual(errors,[]);pass('No page or console errors');
  await capture({path:'qa/overview-light.png'});
  await fs.writeFile('qa/check-results.json',JSON.stringify({checks,errors},null,2));
} finally { await browser.close(); }
