import React,{useEffect,useMemo,useState} from 'react';
import {isStatic,assetUrl,dataUrl} from './deployment.mjs';
import {MapTrifold,ChartBar,Files,Info,Sun,Moon,DownloadSimple,MagnifyingGlass,ArrowSquareOut,ArrowClockwise,WarningCircle,CaretRight,X,ArrowLeft,CalendarBlank,CheckCircle,LinkSimple} from '@phosphor-icons/react';
import {CountyMap} from './CountyMap.jsx';
import {MonthTimeline} from './MonthTimeline.jsx';
import {CountyPicker} from './CountyPicker.jsx';
import {Trend} from './Trend.jsx';
import {Drivers,Score,IndicatorTable,CountyNotes,downloadBrief,downloadCurrent} from './Details.jsx';
import {Publications,About} from './Resources.jsx';
import {BAND_COLORS,INDICATORS,createModel,periodLabel,severityInfo,bandsForPeriod,calendarPeriods} from './data-model.mjs';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/inter/latin-700.css';
const readLocation=()=>{const [page,query]=location.hash.slice(1).split('?');const q=new URLSearchParams(query);return {page:['county','publications','about'].includes(page)?page:'overview',county:q.get('county')||'twiceast',period:q.get('period')};};
const nav=[{id:'overview',icon:MapTrifold,label:'National overview'},{id:'county',icon:ChartBar,label:'County profiles'},{id:'publications',icon:Files,label:'Publications'},{id:'about',icon:Info,label:'About & methodology'}];
export function App() {
  const initial=useMemo(readLocation,[]);
  const [payload,setPayload]=useState(null),[geo,setGeo]=useState(null),[error,setError]=useState(''),[refreshing,setRefreshing]=useState(false);
  const [page,setPage]=useState(initial.page),[selected,setSelected]=useState(initial.county),[period,setPeriod]=useState(initial.period),[compare,setCompare]=useState('');
  const [state,setState]=useState('all'),[band,setBand]=useState('all'),[indicator,setIndicator]=useState('band'),[search,setSearch]=useState(''),[tab,setTab]=useState('Overview'),[toast,setToast]=useState('');
  const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('nawg-theme')||'light';}catch{return 'light';}});
  const [view,setView]=useState('map');
  const model=useMemo(()=>payload&&geo?createModel(payload.rows,geo):null,[payload,geo]);
  async function refresh(force=false) {
    setRefreshing(true);setError('');
    try{const [res,boundaries,international]=await Promise.all([fetch(dataUrl(force),{cache:'no-store'}),geo?Promise.resolve(null):fetch(assetUrl('data/counties.geojson')),geo?Promise.resolve(null):fetch(assetUrl('data/international-boundaries.geojson'))]);const data=await res.json();if(!res.ok)throw new Error(data.error);setPayload(data);if(boundaries){if(!boundaries.ok||!international.ok)throw new Error('Map boundaries could not be loaded.');setGeo({...await boundaries.json(),international:await international.json()});}}
    catch(e){setError(e.message);}finally{setRefreshing(false);}
  }
  useEffect(()=>{refresh();},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('nawg-theme',theme);}catch{}},[theme]);
  useEffect(()=>{if(!model)return;if(!calendarPeriods(model.periods).includes(period))setPeriod(model.defaultPeriod);if(!model.counties.some(c=>c.key===selected))setSelected('twiceast');},[model]);
  useEffect(()=>{if(model&&period)setCompare(model.periods.filter(p=>p<period).at(-1)||'');},[period,model]);
  useEffect(()=>{if(period)history.replaceState(null,'','#'+page+'?'+new URLSearchParams({county:selected||'',period}));},[page,period,selected]);
  useEffect(()=>{const handler=()=>{const s=readLocation();setPage(s.page);setSelected(s.county);if(s.period)setPeriod(s.period);};addEventListener('popstate',handler);addEventListener('hashchange',handler);return()=>{removeEventListener('popstate',handler);removeEventListener('hashchange',handler);};},[]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(id);},[toast]);
  const filtered=useMemo(()=>model?model.counties.filter(c=>(state==='all'||c.state===state)&&(band==='all'||(band==='none'?!model.cells.get(period+'/'+c.key)?.row:model.cells.get(period+'/'+c.key)?.band===band))):[],[model,state,band,period]);
  const visibleKeys=useMemo(()=>new Set(filtered.map(c=>c.key)),[filtered]);
  const allKeys=useMemo(()=>new Set(model?.counties.map(c=>c.key)),[model]);
  const cell=model?.cells.get(period+'/'+selected),county=model?.counties.find(c=>c.key===selected),coverage=model?.coverage[period];
  const BANDS=model&&period?bandsForPeriod(model,period):[];
  if(band!=='all'&&band!=='none'&&!BANDS.includes(band))BANDS.push(band);
  function navigate(id){history.pushState(null,'','#'+id+'?'+new URLSearchParams({county:selected||'',period:period||''}));setPage(id);setTab('Overview');}
  function chooseCounty(key){setSelected(key);setSearch('');if(!visibleKeys.has(key)){setState('all');setBand('all');}}
  const downloadCSV=()=>{downloadCurrent(model,filtered,period);setToast('Selected-period data downloaded');};
  const brief=()=>{if(county){downloadBrief(county,cell,period,payload);setToast('County brief downloaded · open to print or save as PDF');}};
  async function share(){try{await navigator.clipboard.writeText(location.href);setToast(isStatic?'Link copied · share this view with partners':'Link copied · available on this computer');}catch{setToast('Copy the browser address to retain this selection.');}}
  if(!model||!period)return <div className="loading-page"><MapTrifold size={42} weight="duotone"/><h1>NAWG <span>/ South Sudan</span></h1><p>{error||'Loading county evidence and boundaries…'}</p>{error&&<button className="primary" onClick={()=>refresh()}>Retry connection</button>}</div>;
  const states=[...new Set(model.counties.map(c=>c.state))].sort(),isCounty=page==='county',suggestions=search?model.counties.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())).slice(0,7):[];
  return <div className="app-shell"><aside className="nav-rail"><div className="rail-brand"><MapTrifold size={27} weight="duotone"/></div><nav>{nav.map(({id,icon:Icon,label})=><button key={id} className={page===id?'nav-item active':'nav-item'} aria-label={label} title={label} onClick={()=>navigate(id)}><Icon size={23} weight={page===id?'fill':'regular'}/><span className="nav-tooltip">{label}</span></button>)}</nav><div className="rail-bottom"><span>SS</span></div></aside>
    <div className="app-main"><header className="topbar"><a className="brand" href="#overview" onClick={e=>{e.preventDefault();navigate('overview');}}><strong>NAWG</strong><span className="brand-slash">/</span><b>South Sudan</b></a><span className="page-label">{nav.find(n=>n.id===page)?.label}</span><div className="topbar-right"><button className="sync-status" onClick={()=>refresh(true)} disabled={refreshing} title={(isStatic?'Published snapshot · reload latest published data. Retrieved ':'Snapshot retrieved ')+new Date(payload.fetchedAt).toLocaleString()}><ArrowClockwise className={refreshing?'spinning':''}/><span>{refreshing?'Refreshing…':isStatic?'Monthly snapshot':'ActivityInfo connected'}</span></button><div className="segmented theme-switch" aria-label="Colour theme"><button aria-label="Light mode" aria-pressed={theme==='light'} className={theme==='light'?'active':''} onClick={()=>setTheme('light')}><Sun/><span>Light</span></button><button aria-label="Dark mode" aria-pressed={theme==='dark'} className={theme==='dark'?'active':''} onClick={()=>setTheme('dark')}><Moon/><span>Dark</span></button></div></div></header>
    {(page==='overview'||isCounty)&&<div className={'filters '+(isCounty?'county-filters':'')}>{isCounty?<CountyPicker counties={model.counties} selected={selected} onSelect={chooseCounty}/>:<CalendarBlank className="filter-calendar" size={20}/>}
      <label className="filter-field period-filter"><span>Period</span><select aria-label="Reporting period" value={period} onChange={e=>setPeriod(e.target.value)}>{calendarPeriods(model.periods).reverse().map(p=><option key={p} value={p}>{periodLabel(p)}</option>)}</select></label>
      {isCounty?<><label className="filter-field"><span>Compare with</span><select aria-label="Comparison period" value={compare} onChange={e=>setCompare(e.target.value)}><option value="">No comparison</option>{model.periods.filter(p=>p!==period).reverse().map(p=><option key={p} value={p}>{periodLabel(p)}</option>)}</select></label><button className="secondary brief-button" onClick={brief}><DownloadSimple/>Download county brief</button></>:<>
      <label className="filter-field"><span>State</span><select aria-label="State" value={state} onChange={e=>setState(e.target.value)}><option value="all">All states</option>{states.map(s=><option key={s}>{s}</option>)}</select></label>
      <label className="filter-field indicator-filter"><span>Indicator</span><select aria-label="Map indicator" value={indicator} onChange={e=>setIndicator(e.target.value)}><option value="band">Needs severity band</option>{INDICATORS.map(i=><option key={i.id} value={i.severity}>{i.label}</option>)}</select></label>
      <label className="filter-field"><span>Band</span><select aria-label="Band" value={band} onChange={e=>setBand(e.target.value)}><option value="all">All bands</option>{BANDS.map(b=><option key={b}>{b}</option>)}<option value="none">No data / review</option></select></label>
      <div className="county-search"><MagnifyingGlass/><input aria-label="Search county" placeholder="Search county…" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setSearch('');if(e.key==='Enter'&&suggestions.length)chooseCounty(suggestions[0].key);}}/>{search&&<div className="search-results">{suggestions.length?suggestions.map(c=><button key={c.key} onClick={()=>chooseCounty(c.key)}><span>{c.name}</span><small>{c.state}</small></button>):<p>No matching county</p>}</div>}</div></>}
    </div>}
    {(error||payload.warning)&&<div className="status-banner warning"><WarningCircle/>{error||payload.warning}</div>}
    {page==='overview'&&<main className="overview-page"><div className="overview-grid"><section className="national-map-section"><div className="map-title"><div><h1>South Sudan</h1><p>County needs <span>·</span> {periodLabel(period,false)}</p></div><div className="segmented small"><button className={view==='map'?'active':''} onClick={()=>setView('map')}>Map</button><button className={view==='table'?'active':''} onClick={()=>setView('table')}>Table</button></div></div>
      {view==='map'?<CountyMap model={model} period={period} selected={selected} onSelect={chooseCounty} visibleKeys={visibleKeys} indicator={indicator}/>:<div className="county-table-wrap"><table className="county-table"><thead><tr><th>County</th><th>State</th><th>Score</th><th>Band</th></tr></thead><tbody>{filtered.map(c=>{const x=model.cells.get(period+'/'+c.key);return <tr key={c.key} className={c.key===selected?'selected':''}><td><button onClick={()=>chooseCounty(c.key)}>{c.name}</button></td><td>{c.state}</td><td>{x?.score?.toFixed(2)??'—'}</td><td>{x?.conflict?'Review':x?.row?x.band:'No data'}</td></tr>;})}</tbody></table></div>}
      {view==='map'&&<div className="map-legend"><span>{indicator==='band'?'Needs severity band':'Indicator classification'}</span><div>{(indicator==='band'?BANDS:indicator.includes('phase')?['Phase 1','Phase 2','Phase 3','Phase 4','Phase 5']:['Low','Moderate','High','Very High']).map(b=><button key={b} className={band===b?'legend-active':''} title={indicator==='band'?'Filter band '+b:b} onClick={()=>{if(indicator==='band')setBand(band===b?'all':b);}}><i style={{background:indicator==='band'?BAND_COLORS[b]:severityInfo(b).color}}/>{b}</button>)}<span className="legend-none"><i/>No data</span></div></div>}
      {filtered.length===0&&<div className="map-empty"><strong>No counties match these filters</strong><button className="text-button" onClick={()=>{setState('all');setBand('all');}}>Reset filters</button></div>}
      <MonthTimeline model={model} period={period} onPeriod={setPeriod}/>
    </section><aside className="county-inspector"><div className="inspector-heading"><div><span className="eyebrow">Selected county</span><h1>{county?.name||'Choose a county'}</h1><p>{county?.state}</p></div><button className="icon-button" onClick={share} aria-label="Copy current view link" title="Copy current view link"><LinkSimple/></button></div>
      {(state!=='all'||band!=='all')&&<div className={'selection-notice '+(visibleKeys.has(selected)?'selection-notice-reserved':'')} aria-hidden={visibleKeys.has(selected)?true:undefined}>Selected county is outside the map filters.<button tabIndex={visibleKeys.has(selected)?-1:0} onClick={()=>{setState('all');setBand('all');}}>Clear filters</button></div>}<Score cell={cell}/><Drivers cell={cell} onAbout={()=>navigate('about')}/><div className="inspector-actions"><button className="primary" onClick={()=>navigate('county')}>Open county profile <ArrowSquareOut/></button><button className="secondary" onClick={downloadCSV} title="Download current filtered counties"><DownloadSimple/><span>Data</span></button></div>
    </aside></div><div className="coverage-bar"><span className="coverage-dot"/><span><strong>{coverage?.valid??0} of {model.counties.length}</strong> counties with usable scores · {periodLabel(period)}</span>{coverage?.conflicts>0&&<span className="coverage-review">{coverage.conflicts} need review</span>}<button onClick={()=>navigate('about')}>Coverage & sources <CaretRight/></button></div><Trend model={model} selected={selected} period={period} compare={null} onPeriod={setPeriod}/></main>}
    {isCounty&&<main className="county-page"><div className="county-heading"><div><button className="breadcrumb" onClick={()=>navigate('overview')}><ArrowLeft/>Counties <span>/</span> {county?.state}</button><h1>{county?.name} County</h1></div><Score cell={cell} compact/><div className="comparison-summary">{compare&&<><small>Compared with {periodLabel(compare)}</small><strong>{cell?.score!=null&&model.cells.get(compare+'/'+selected)?.score!=null?((cell.score-model.cells.get(compare+'/'+selected).score)>0?'+':'')+(cell.score-model.cells.get(compare+'/'+selected).score).toFixed(2):'—'} <span>points</span></strong></>}</div><button className="icon-button" aria-label="Copy county link" onClick={share}><LinkSimple/></button></div><div className="tabs" role="tablist">{['Overview','Indicator data','Notes & sources'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
      <div className="county-coverage">{coverage?<>Data available for <strong>{coverage.valid} of {model.counties.length} counties</strong> in {periodLabel(period)}.</>:'No county reports are available for this month.'}<button className="text-button" onClick={()=>navigate('about')}>About coverage</button></div>
      {tab==='Overview'?<><div className="county-content"><section className="county-context" aria-label="County map"><CountyMap model={model} period={period} selected={selected} onSelect={chooseCounty} visibleKeys={allKeys} countyMode/></section><Drivers cell={cell} full onAbout={()=>navigate('about')}/></div><Trend model={model} selected={selected} period={period} compare={compare} onPeriod={setPeriod} countyPage/><button className="notes-link" onClick={()=>setTab('Notes & sources')}>Notes & sources <CaretRight/></button></>:tab==='Indicator data'?<IndicatorTable key={selected+'/'+period} cell={cell}/>:<CountyNotes cell={cell} model={model}/>}</main>}
    {page==='publications'&&<Publications period={period} county={county} filtered={filtered} payload={payload} onCSV={downloadCSV} onBrief={brief}/>}
    {page==='about'&&<About model={model} payload={payload} onPeriod={p=>{setPeriod(p);navigate('overview');}}/>}
    </div>{toast&&<div className="toast" role="status"><CheckCircle/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X/></button></div>}
  </div>;
}
