import React,{useEffect,useMemo,useState} from 'react';
import {MapTrifold,ChartBar,ChartLine,Files,Info,Sun,Moon,DownloadSimple,ArrowSquareOut,CaretRight,X,ArrowLeft,CheckCircle,LinkSimple,ArrowsLeftRight,Table,SquaresFour} from '@phosphor-icons/react';
import {assetUrl,isStatic,dataUrl} from './deployment.mjs';
import {CountyMap} from './CountyMap.jsx';
import {MonthTimeline} from './MonthTimeline.jsx';
import {CountyPicker} from './CountyPicker.jsx';
import {ResetButton} from './ResetButton.jsx';
import {Trend} from './Trend.jsx';
import {Drivers,Score,IndicatorTable,CountyNotes,downloadBrief,downloadCurrent} from './Details.jsx';
import {KPIs,NationalCharts,TrendAnalysis,ChangeAnalysis,DataExplorer,DriverAnalysis,PageHeading,ClassificationAnalysis} from './Analysis.jsx';
import {Downloads,Methodology} from './Evidence.jsx';
import {createModel,INDICATORS,periodLabel,severityInfo,bandsForPeriod,calendarPeriods} from './data-model.mjs';
import {archiveModel,colorsFor,comparable,previousPeriod} from './analytics-model.mjs';
import archive from '../data/nawg-archive.json';
import activitySnapshot from '../data/nawg-public.json';
import reachLogo from './assets/reach.png';
import ochaLogo from './assets/ocha.png';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/inter/latin-700.css';
const nav=[{id:'overview',icon:MapTrifold,label:'National overview'},{id:'county',icon:ChartBar,label:'County profiles'},{id:'trends',icon:ChartLine,label:'Trends & persistent needs'},{id:'compare',icon:ArrowsLeftRight,label:'Change analysis'},{id:'drivers',icon:SquaresFour,label:'Needs drivers'},{id:'data',icon:Table,label:'Data explorer'},{id:'publications',icon:Files,label:'Publications & downloads'},{id:'about',icon:Info,label:'Methodology & sources'}];
const readLocation=()=>{const [page,query]=location.hash.slice(1).split('?'),q=new URLSearchParams(query);return {page:nav.some(n=>n.id===page)?page:'overview',county:q.get('county')||'twiceast',period:q.get('period')||null,source:q.get('source')==='activityinfo'?'activityinfo':'archive'};};
export function App(){
 const initial=useMemo(readLocation,[]);
 const [geo,setGeo]=useState(null),[error,setError]=useState(''),[payload,setPayload]=useState(activitySnapshot);
 const [page,setPage]=useState(initial.page),[source,setSource]=useState(initial.source),[selected,setSelected]=useState(initial.county),[period,setPeriod]=useState(initial.period),[compare,setCompare]=useState('');
 const [state,setState]=useState('all'),[band,setBand]=useState('all'),[indicator,setIndicator]=useState('band'),[tab,setTab]=useState('Overview'),[toast,setToast]=useState('');
 const [resetVersion,setResetVersion]=useState(0);
 const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('nawg-theme')||'light';}catch{return 'light';}});
 const model=useMemo(()=>{if(!geo)return null;return source==='archive'?archiveModel(archive,geo):{...createModel(payload.rows,geo),sourceKind:'activityinfo',sourceLabel:'ActivityInfo snapshot',indicators:INDICATORS};},[geo,source,payload]);
 async function loadMap(){setError('');try{const responses=await Promise.all(['counties.geojson','international-boundaries.geojson'].map(n=>fetch(assetUrl('data/'+n))));if(responses.some(r=>!r.ok))throw Error('Map files could not be loaded.');const [counties,international]=await Promise.all(responses.map(r=>r.json()));setGeo({...counties,international});}catch(e){setError(e.message);}}
 useEffect(()=>{loadMap();},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('nawg-theme',theme);}catch{}},[theme]);
 useEffect(()=>{if(!model)return;if(!calendarPeriods(model.periods).includes(period))setPeriod(model.defaultPeriod);if(!model.counties.some(c=>c.key===selected))setSelected('twiceast');},[model]);
 useEffect(()=>{if(model&&period)setCompare(previousPeriod(model,period));},[model,period]);
 useEffect(()=>{if(period)history.replaceState(null,'','#'+page+'?'+new URLSearchParams({county:selected,period,source}));},[page,selected,period,source]);
 useEffect(()=>{const handler=()=>{const s=readLocation();setPage(s.page);setSelected(s.county);setSource(s.source);setPeriod(s.period);setTab('Overview');};addEventListener('popstate',handler);addEventListener('hashchange',handler);return()=>{removeEventListener('popstate',handler);removeEventListener('hashchange',handler);};},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{if(resetVersion)document.querySelector('.reset-filters')?.focus({preventScroll:true});},[resetVersion]);
 const scope=useMemo(()=>model?model.counties.filter(c=>state==='all'||c.state===state):[],[model,state]);
 const filtered=useMemo(()=>scope.filter(c=>band==='all'||(band==='none'?!model.cells.get(period+'/'+c.key)?.row:model.cells.get(period+'/'+c.key)?.band===band)),[scope,model,period,band]);
 const visibleKeys=useMemo(()=>new Set(filtered.map(c=>c.key)),[filtered]),allKeys=useMemo(()=>new Set(model?.counties.map(c=>c.key)),[model]);
 const county=model?.counties.find(c=>c.key===selected),cell=model?.cells.get(period+'/'+selected),colors=colorsFor(model);
 function navigate(id){history.pushState(null,'','#'+id+'?'+new URLSearchParams({county:selected,period:period||'',source}));setPage(id);setTab('Overview');window.scrollTo({top:0,behavior:'instant'});}
 function chooseCounty(key){setSelected(key);if(!visibleKeys.has(key)){setState('all');setBand('all');}}
 function openCounty(key){chooseCounty(key);navigate('county');}
 function changeSource(value){setSource(value);setPeriod(null);setBand('all');setIndicator('band');setState('all');}
 function resetPage(){setResetVersion(v=>v+1);setToast('Page controls reset. Evidence source and theme kept.');}
 function resetFilters(){
  setState('all');setBand('all');setIndicator('band');
  setPeriod(model.defaultPeriod);setCompare(previousPeriod(model,model.defaultPeriod));
  setSelected(model.counties.some(c=>c.key==='twiceast')?'twiceast':model.counties[0].key);
  setTab('Overview');setResetVersion(v=>v+1);
  setToast('Filters and page controls reset to defaults. Evidence source and theme kept.');
 }
 function downloadCSV(){downloadCurrent(model,filtered,period);setToast('Filtered county data downloaded.');}
 function brief(){downloadBrief(county,cell,period,source==='archive'?{...archive,publicSnapshot:true}:payload);setToast('County brief downloaded. Open it to print or save as PDF.');}
 async function share(){try{await navigator.clipboard.writeText(location.href);setToast('Link copied with county, cycle and evidence source.');}catch{setToast('Copy the browser address to share this view.');}}
 async function refreshActivity(){try{const r=await fetch(dataUrl(true),{cache:'no-store'});if(!r.ok)throw Error('ActivityInfo could not be refreshed.');setPayload(await r.json());setToast('ActivityInfo refreshed for this local session.');}catch(e){setToast(e.message);}}
 if(!model||!period)return <div className="loading-page"><MapTrifold size={42}/><h1>Needs Analysis Working Group</h1><p>{error||'Preparing the evidence and map…'}</p>{error&&<button className="primary" onClick={loadMap}>Retry</button>}</div>;
 const analytical=!['publications','about'].includes(page),BANDS=source==='archive'?archive.bands.map(b=>b.id):bandsForPeriod(model,period),cycle=model.cycles?.find(c=>c.id===period),comparison=model.cells.get(compare+'/'+selected),delta=comparable(model,period,compare)&&cell?.score!=null&&comparison?.score!=null?cell.score-comparison.score:null;
 return <div className="app-shell combined-app"><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content').focus();}}>Skip to content</a><aside className="nav-rail"><button className="rail-brand" aria-label="NAWG home" onClick={()=>navigate('overview')}><MapTrifold size={28} weight="duotone"/></button><nav>{nav.map(({id,icon:Icon,label})=><button key={id} className={'nav-item '+(page===id?'active':'')} aria-label={label} aria-current={page===id?'page':undefined} title={label} onClick={()=>navigate(id)}><Icon size={23} weight={page===id?'fill':'regular'}/><span className="nav-tooltip">{label}</span></button>)}</nav><div className="rail-bottom"><button className="nav-item" aria-label={theme==='light'?'Switch to dark mode':'Switch to light mode'} title={theme==='light'?'Dark mode':'Light mode'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={22}/>:<Sun size={22}/>}</button><span>SSD</span></div></aside>
 <div className="app-main"><header className="topbar"><a className="full-brand" href="#overview" onClick={e=>{e.preventDefault();navigate('overview');}}><strong>Needs Analysis Working Group (NAWG)</strong><span>South Sudan</span></a><div className="partner-logos" aria-label="REACH and OCHA"><img className="reach-logo" src={reachLogo} alt="REACH"/><span className="logo-divider"/><span className="ocha-logo-crop"><img src={ochaLogo} alt="United Nations OCHA"/></span></div></header>
 {analytical&&<div className="filters"><label className="filter-field evidence-filter"><span>Evidence source</span><select aria-label="Evidence source" value={source} onChange={e=>changeSource(e.target.value)}><option value="archive">NAWG analysis archive</option><option value="activityinfo">ActivityInfo snapshot</option></select></label><label className="filter-field period-filter"><span>{source==='archive'?'Analysis cycle':'Reporting month'}</span><select aria-label="Reporting period" value={period} onChange={e=>setPeriod(e.target.value)}>{calendarPeriods(model.periods).reverse().map(p=><option key={p} value={p}>{periodLabel(p)}</option>)}</select></label>
 {page!=='county'&&<label className="filter-field"><span>State</span><select aria-label="State" value={state} onChange={e=>setState(e.target.value)}><option value="all">All states</option>{[...new Set(model.counties.map(c=>c.state))].sort().map(s=><option key={s}>{s}</option>)}</select></label>}
 {page==='overview'&&<label className="filter-field indicator-filter"><span>Map layer</span><select aria-label="Map indicator" value={indicator} onChange={e=>setIndicator(e.target.value)}><option value="band">Needs severity band</option><option value="score">Needs severity score</option>{source==='archive'&&<><option value="hpc:2026">HNRP severity · 2026 (annual)</option><option value="hpc:2025">HNRP severity · 2025 (annual)</option></>}<option value="change">Score change vs previous cycle</option>{model.indicators.map(i=><option key={i.id} value={i.severity}>{i.label}</option>)}</select></label>}
 {['overview','data'].includes(page)&&<label className="filter-field band-filter"><span>Band</span><select aria-label="Band" value={band} onChange={e=>setBand(e.target.value)}><option value="all">All bands</option>{BANDS.map(b=><option key={b}>{b}</option>)}<option value="none">No data / review</option></select></label>}
 <CountyPicker key={resetVersion} counties={model.counties} selected={selected} onSelect={chooseCounty}/>
 {page==='county'&&<><label className="filter-field"><span>Compare with</span><select aria-label="Comparison period" value={compare} onChange={e=>setCompare(e.target.value)}><option value="">No comparison</option>{model.periods.filter(p=>p!==period).reverse().map(p=><option key={p} value={p}>{periodLabel(p)}</option>)}</select></label><button className="secondary brief-button" onClick={brief}><DownloadSimple/>County brief</button></>}<ResetButton onReset={resetFilters}/></div>}
 {/* Only an explicit reset remounts page controls and the map; playback must retain its camera. */}
 <div id="main-content" key={resetVersion} tabIndex={-1}>
 {page==='overview'&&<main className="overview-page"><KPIs model={model} counties={filtered} period={period} compare={compare} onCompare={()=>navigate('compare')}/><div className="overview-grid"><section className="national-map-section"><div className="map-title"><div><span className="eyebrow">COUNTY NEEDS</span><h1>{state==='all'?'South Sudan':state}</h1><p>{indicator.startsWith('hpc:')?'HNRP '+indicator.slice(4)+' · annual reference, independent of cycle':periodLabel(period,false)+(cycle?' · '+cycle.window:'')}</p></div><button className="map-data-button secondary" onClick={()=>navigate('data')}><Table/>Data</button></div><CountyMap {...{model,period,selected,visibleKeys,indicator,compare}} onSelect={chooseCounty}/><div className="map-legend"><span>{indicator==='band'?'Needs severity band':indicator==='score'?'Final NSS · 0–10':indicator.startsWith('hpc:')?'Annual HNRP severity · 1–5':indicator==='change'?'Change vs '+periodLabel(compare):'Indicator classification'}</span><div>{indicator==='band'?BANDS.map(b=><button key={b} onClick={()=>setBand(band===b?'all':b)} className={band===b?'legend-active':''}><i style={{background:colors[b]}}/>{b}</button>):indicator==='score'?<><i style={{background:'#e4f0fc'}}/>Low<i style={{background:'#065cb2'}}/>High</>:indicator==='change'?<><i style={{background:'#329d93'}}/>Falling<i style={{background:'#f6f5ed'}}/>Unchanged<i style={{background:'#dc4b57'}}/>Rising</>:(indicator.startsWith('hpc:')||indicator.includes('phase')?['Phase 1','Phase 2','Phase 3','Phase 4','Phase 5']:['None recorded','Low','Moderate','High','Very High']).map(b=><span key={b} className="legend-none"><i style={{background:severityInfo(b).color}}/>{indicator.startsWith('hpc:')?b.replace('Phase ',''):b}</span>)}<span className="legend-none"><i/>No data</span></div></div>{!filtered.length&&<div className="map-empty"><strong>No counties match these filters</strong><button className="text-button" onClick={resetFilters}>Reset filters</button></div>}<MonthTimeline key={source} model={model} period={period} onPeriod={setPeriod}/></section>
 <aside className="county-inspector"><div className="inspector-heading"><div><span className="eyebrow">SELECTED COUNTY</span><h1>{county?.name}</h1><p>{county?.state}{!visibleKeys.has(selected)&&<span className="selected-outside"> · outside map filters</span>}</p></div><button className="icon-button" aria-label="Copy current view link" onClick={share}><LinkSimple/></button></div><Score cell={cell}/><div className="county-change"><span>{delta==null?'No comparable previous score':(delta>0?'+':'')+delta.toFixed(2)+' points vs '+periodLabel(compare)}</span>{cell?.row?.adjustment&&cell.row.adjustment!=='No adjustment'&&<b>{cell.row.adjustment}</b>}</div><Drivers cell={cell} model={model} onAbout={()=>navigate('about')}/><div className="inspector-actions"><button className="primary" onClick={()=>navigate('county')}>Open county profile<ArrowSquareOut/></button><button className="secondary" onClick={brief} aria-label="Download selected county brief"><DownloadSimple/></button></div></aside></div>
 <div className="coverage-bar"><span className="coverage-dot"/><span>{model.sourceLabel} · {model.coverage[period]?.valid??0} of {model.counties.length} counties with usable scores · {state==='all'?'All states':state}{band!=='all'?' · Band filter: '+band:''}</span><button onClick={()=>navigate('about')}>Coverage & sources<CaretRight/></button></div><NationalCharts {...{model,period}} counties={filtered} onPeriod={setPeriod} compact/><Trend {...{model,selected,period}} onPeriod={setPeriod}/><div className="overview-analysis-links"><button onClick={()=>navigate('trends')}>Explore persistent needs <ArrowSquareOut/></button><button onClick={()=>navigate('compare')}>Compare cycle changes <ArrowSquareOut/></button><button onClick={()=>navigate('drivers')}>Explore needs drivers <ArrowSquareOut/></button></div></main>}
 {page==='county'&&<main className="county-page"><div className="county-heading"><div><button className="breadcrumb" onClick={()=>navigate('overview')}><ArrowLeft/>Counties<span>/</span>{county?.state}</button><h1>{county?.name} County</h1></div><Score cell={cell} compact/><div className="comparison-summary"><small>Compared with {periodLabel(compare)}</small><strong>{delta==null?'Not comparable':(delta>0?'+':'')+delta.toFixed(2)}{delta!=null&&<span> points</span>}</strong></div><button className="icon-button" aria-label="Copy county link" onClick={share}><LinkSimple/></button></div>
 <div className="county-evidence-row"><span>{cycle?cycle.window:periodLabel(period,false)} · {model.sourceLabel}</span>{cell?.row?.adjustment&&<span>{cell.row.adjustment}</span>}{source==='archive'&&<span>Annual HNRP severity: 2025 <b>{model.hpcByCounty?.[selected]?.[2025]??'—'}/5</b> · 2026 <b>{model.hpcByCounty?.[selected]?.[2026]??'—'}/5</b></span>}</div><div className="tabs" role="tablist">{['Overview','Indicator data','Notes & sources'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Overview'?<><div className="county-content"><section className="county-context" aria-label="County map"><CountyMap {...{model,period,selected}} onSelect={chooseCounty} visibleKeys={allKeys} countyMode/></section><Drivers {...{cell,model}} full onAbout={()=>navigate('about')}/></div><Trend {...{model,selected,period,compare}} onPeriod={setPeriod} countyPage/></>:tab==='Indicator data'?<IndicatorTable key={selected+'/'+period+'/'+source} {...{cell,model}}/>:<CountyNotes {...{cell,model}}/>}</main>}
 {page==='trends'&&<TrendAnalysis {...{model,period}} counties={scope} onPeriod={setPeriod} onCounty={openCounty}/>}
 {page==='compare'&&<ChangeAnalysis {...{model,period,compare,setCompare}} counties={scope} onCounty={openCounty}/>}
 {page==='drivers'&&<main className="analysis-page"><PageHeading eyebrow="WHAT IS DRIVING NEEDS?" title="Needs drivers & classification" text="Explore vulnerability, triggers, and the decisions behind final classifications."/><DriverAnalysis {...{model,period}} counties={scope}/><ClassificationAnalysis {...{model,period}} counties={scope}/></main>}
 {page==='data'&&<DataExplorer {...{model,period}} counties={filtered} onCounty={openCounty}/>}
 {page==='publications'&&<Downloads {...{archive,period,county}} onCSV={downloadCSV} onBrief={brief} onReset={resetPage}/>}
 {page==='about'&&<Methodology {...{model,archive}} onReset={resetPage} onPeriod={p=>{setPeriod(p);navigate('overview');}}/>}
 </div><footer className="app-footer"><span>NAWG · South Sudan / {model.sourceLabel}{source==='archive'?' · Prepared '+archive.built:''}</span><button onClick={()=>navigate('about')}>Methods & sources</button>{!isStatic&&source==='activityinfo'&&<button onClick={refreshActivity}>Refresh local ActivityInfo</button>}<small>Monthly static release · no live credentials in the published site</small></footer></div>{toast&&<div className="toast" role="status"><CheckCircle/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X/></button></div>}</div>;
}
