import React,{useState} from 'react';
import {isStatic} from './deployment.mjs';
import {WarningCircle,ArrowSquareOut,Users,ShieldCheck,FirstAid,Plant,Heartbeat,ChartLine,Person,ArrowsLeftRight,CaretDown,CaretUp,SquaresFour,Table} from '@phosphor-icons/react';
import {INDICATORS,BAND_COLORS,severityInfo,periodLabel,csvText,periodKey} from './data-model.mjs';
import {indicatorsFor,cellColor,colorsFor} from './analytics-model.mjs';
import {downloadFile} from './Trend.jsx';
export function SeverityMark({value}) {
  const s=severityInfo(value);
  return <span className="severity-mark" style={{'--severity':s.color}} title={s.label}><span className="severity-steps" aria-hidden="true">{Array.from({length:s.max},(_,i)=><i key={i} className={i<s.level?'filled':''}/>)}</span><span className="severity-label">{s.label==='Not classified'?'Unclassified':s.label}</span></span>;
}
export function Drivers({cell,full=false,onAbout,model}) {
  const indicators=model?.indicators||indicatorsFor(cell);
  return <section className={'drivers '+(full?'expanded-drivers':'')}><div className="section-heading"><div><h2>What is driving needs?</h2>{full&&<p>Source-reported indicators for the selected period</p>}</div>{full&&<button className="text-button" onClick={onAbout}>Methodology <ArrowSquareOut/></button>}</div>
    <div className="driver-values-slot">{cell?.conflict&&<div className="data-message"><WarningCircle/><div><strong>Conflicting source records</strong><p>This county has {cell.records.length} different records for this month. Review them in Indicator data.</p></div></div>}<div className={'driver-groups '+(cell?.conflict?'unresolved-drivers':'')} aria-hidden={cell?.conflict?true:undefined}>{['Underlying vulnerability','First-level triggers'].map(group=><div key={group} className="driver-group"><h3>{group}</h3>{indicators.filter(i=>i.group===group).map(i=><div className={'indicator-row indicator-'+i.id} key={i.id} title={i.severity}><span>{i.label}</span><SeverityMark value={cell?.row?.[i.severity]||'No data'}/></div>)}</div>)}</div></div>
    <p className="source-footnote">Source: ActivityInfo · climate and conflict included from December 2025. Earlier values may be unclassified.</p></section>;
}
export function Score({cell,compact=false}) {
  return <div className={'score-summary '+(compact?'compact':'')}><div><span className="eyebrow">Needs severity score</span><strong className="score-value">{cell?.score!=null?cell.score.toFixed(2):'—'}</strong></div><div><span className="band-pill" style={{'--band-color':cellColor(cell),color:cell?.band==='A'?'white':undefined}}>{cell?.conflict?'Review needed':cell?.row?'Band '+cell.band:'No data'}</span>{cell?.row?.NSS_severity&&<span className="source-severity">{cell.row.NSS_severity}</span>}</div></div>;
}
export function IndicatorTable({cell,model}) {
  const indicators=model?.indicators||indicatorsFor(cell);
  const [group,setGroup]=useState('All indicators'),[view,setView]=useState('cards'),[expanded,setExpanded]=useState(null),[variant,setVariant]=useState(0);
  if(!cell)return <div className="empty-inline">No records are available for this county and period.</div>;
  const r=cell.conflict?cell.records[variant]:cell.row,items=indicators.filter(i=>group==='All indicators'||i.group===group);
  const icons={demographic:Person,stock:Users,ipcAverage:ChartLine,protection:ShieldCheck,flow:ArrowsLeftRight,disease:FirstAid,food:Plant,nutrition:Heartbeat,climate:Plant,conflict:ShieldCheck};
  return <section className="indicator-data"><div className="indicator-explorer-heading"><div><h2>Explore the indicators</h2><p>Select an indicator to see its source values.</p></div><div className="segmented small"><button className={view==='cards'?'active':''} onClick={()=>setView('cards')} aria-label="Indicator cards"><SquaresFour/>Cards</button><button className={view==='table'?'active':''} onClick={()=>setView('table')} aria-label="Indicator table"><Table/>Table</button></div></div>
    {cell.conflict&&<div className="conflict-picker"><WarningCircle/><div><strong>Conflicting submissions — review needed</strong><p>Compare each submission below. None is treated as the resolved county result.</p></div><select aria-label="Source submission" value={variant} onChange={e=>{setVariant(Number(e.target.value));setExpanded(null);}}>{cell.records.map((_,i)=><option key={i} value={i}>Submission {String.fromCharCode(65+i)}</option>)}</select></div>}
    <div className="indicator-group-filter" aria-label="Indicator group">{['All indicators','Underlying vulnerability','First-level triggers'].map(g=><button key={g} aria-pressed={group===g} className={group===g?'active':''} onClick={()=>setGroup(g)}>{g}<span>{g==='All indicators'?indicators.length:indicators.filter(i=>i.group===g).length}</span></button>)}</div>
    {view==='cards'?<div className="indicator-card-grid">{items.map(i=>{const severity=severityInfo(r?.[i.severity]),Icon=icons[i.id],open=expanded===i.id;return <article key={i.id} className={'indicator-card '+(open?'expanded':'')} style={{'--indicator-color':severity.color}}><button className="indicator-card-trigger" aria-expanded={open} onClick={()=>setExpanded(open?null:i.id)}><div className="indicator-card-top"><span className="indicator-icon"><Icon size={24} weight="duotone"/></span><span className="classification-pill">{severity.label}</span></div><h3>{i.label}</h3><SeverityMark value={r?.[i.severity]||'No data'}/><div className="indicator-card-bottom"><span>{i.group}</span>{open?<CaretUp/>:<CaretDown/>}</div></button>{open&&<div className="indicator-card-detail"><dl><div><dt>Source input</dt><dd>{r?.[i.field]??'Not provided'}</dd></div><div><dt>Classification</dt><dd>{r?.[i.severity]??'Not provided'}</dd></div></dl><p>Source input is indicator-specific; it is not a percentage or directly comparable with other indicator inputs.</p></div>}</article>;})}</div>:<div className="indicator-table-scroll"><table><thead><tr><th>Indicator</th><th>Source input</th><th>Classification</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.label}</td><td>{r?.[i.field]??'—'}</td><td><SeverityMark value={r?.[i.severity]||'No data'}/></td></tr>)}</tbody></table></div>}
    <details className="score-audit"><summary>First-level & final needs scores</summary><div className="score-audit-grid">{[['First-level',r?.needs_severity_score_NSS,r?.band],['Final',r?.needs_severity_score_NSS_edited,r?.band_edited]].map(([label,value,band])=><div key={label}><span>{label}</span><strong>{value??'Not supplied'}</strong><span className="band-pill" style={{'--band-color':colorsFor(model,periodKey(r))[band]||'#b9c2cd'}}>{band?'Band '+band:'Not supplied'}</span></div>)}</div></details>
  </section>;
}
export function CountyNotes({cell,model}) {
  return <div className="notes-panel"><h2>Notes & sources</h2><h3>Classification context</h3><p>{cell?.row?.classification_context||'No resolved record for this period'}</p><h3>County notes</h3>{cell?.notes?.length?cell.notes.map((n,i)=><p key={i}>{n}</p>):<p>Free-text county notes are kept private and are not included in this dashboard.</p>}<h3>How this view is prepared</h3><p>The edited needs score and band are used where supplied, with the original fields as fallback. Indicator classifications are read directly from ActivityInfo. Zero values are preserved.</p><p>Missing months are gaps in the chart. Conflicting county/month records are excluded from displayed scores and remain available in Indicator data. Identical metric duplicates are collapsed.</p><p>Bands are displayed exactly as reported for each period. Historical categories are not converted into newer classification schemes. Compare periods with this in mind.</p><p>Boundary coverage: {model.counties.length} OCHA polygons. The form's “Abyei Administrative Area” is matched to the boundary layer's “Abyei Region” (SS0001).</p></div>;
}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function downloadBrief(county,cell,period,payload) {
  const rows=indicatorsFor(cell).map(i=>'<tr><td>'+esc(i.label)+'</td><td>'+esc(cell?.row?.[i.severity]||'No data')+'</td></tr>').join('');
  const html='<!doctype html><html lang="en"><meta charset="utf-8"><title>NAWG · '+esc(county.name)+'</title><style>body{font:16px system-ui;max-width:850px;margin:50px auto;color:#14253c}h1{font-size:34px}h2{margin-top:32px}table{border-collapse:collapse;width:100%}td{padding:12px 0;border-bottom:1px solid #ddd}small{color:#526174}button{padding:10px 18px}@media print{button{display:none}}</style><button onclick="window.print()">Print / save as PDF</button><p>NAWG / South Sudan</p><h1>'+esc(county.name)+' County</h1><p>'+esc(county.state)+' · '+esc(periodLabel(period,false))+'</p><h2>Needs severity score: '+(cell?.score!=null?cell.score.toFixed(2):'Not available')+'</h2><p>'+esc(cell?.conflict?'Conflicting source records — review required':cell?.row?'Band '+cell.band:'No data for selected period')+'</p><h2>What is driving needs?</h2><table>'+rows+'</table><h2>Notes</h2><p>'+esc(cell?.notes?.join('\n')||(payload.publicSnapshot?'Free-text county notes are not included in this public release.':'No county notes supplied.'))+'</p><small>Source: '+esc(payload.source||'ActivityInfo snapshot')+'. Prepared: '+esc(payload.built||payload.fetchedAt)+'. Final score and band preferred where supplied. Classifications are not recalculated. Framework: '+esc(cell?.row?.framework||'Source-reported')+'.</small></html>';
  downloadFile('NAWG-'+county.name+'-'+period+'.html',html,'text/html;charset=utf-8');
}
export function downloadCurrent(model,filtered,period) {
  const rows=filtered.flatMap(c=>{const cell=model.cells.get(period+'/'+c.key);return cell?cell.records.map(r=>({...r,quality_status:cell.conflict?'conflicting records':cell.records.length>1?'duplicate metrics':'source record'})):[];});
  downloadFile('NAWG-'+period+'-data.csv',csvText(rows,['County.name','County.parent.name','Year','Month','needs_severity_score_NSS_edited','band_edited','needs_severity_score_NSS','band',...(model.indicators||INDICATORS).flatMap(i=>[i.field,i.severity]),'classification_context','quality_status']));
}
