import React,{useState} from 'react';
import {FilePdf,DownloadSimple,ArrowSquareOut} from '@phosphor-icons/react';
import {assetUrl} from './deployment.mjs';
import {periodLabel} from './data-model.mjs';
import {PageHeading} from './Analysis.jsx';
import {ResetButton} from './ResetButton.jsx';
import frameworkImage from './assets/framework.png';
export function Downloads({reference,period,onCSV,onBrief,county,onReset}){
 const [kind,setKind]=useState('all'),[year,setYear]=useState('all');
 const reports=[...reference.reports].filter(r=>(kind==='all'||r.kind===kind)&&(year==='all'||(r.cycle?r.cycle.startsWith(year):r.title.includes(year)))).sort((a,b)=>(b.cycle||'').localeCompare(a.cycle||''));
 const latest=[...reference.reports].reverse().find(r=>r.kind==='summary');
 return <main className="analysis-page"><PageHeading eyebrow="KNOWLEDGE & EVIDENCE" title="Publications & downloads" text="Final analysis products, methodological guidance, and reusable county data."/><div className="download-feature"><FilePdf size={40} weight="duotone"/><div><span className="eyebrow">LATEST MONTHLY PRODUCT</span><h2>{latest.title}</h2><p>Supplied final PDF · analysis windows and meeting dates may differ</p></div><a className="primary" href={assetUrl(latest.file)} target="_blank" rel="noreferrer"><ArrowSquareOut/>Open PDF</a></div>
 <section className="analysis-card"><div className="card-heading"><div><h2>Publication library</h2><p>{reports.length} supplied products</p></div><div className="chart-options"><select aria-label="Publication type" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All products</option><option value="summary">Monthly summaries</option><option value="trend">Trend analysis</option><option value="framework">Methodology</option></select><select aria-label="Publication year" value={year} onChange={e=>setYear(e.target.value)}><option value="all">All years</option>{['2026','2025','2024'].map(y=><option key={y}>{y}</option>)}</select><ResetButton onReset={onReset} title="Show all publication types and years. Keep the selected evidence source, county, cycle and theme."/></div></div><div className="report-library">{reports.map(r=><article key={r.file}><FilePdf size={29}/><div><span className="report-type">{r.kind==='summary'?'MONTHLY SUMMARY':r.kind==='trend'?'TREND ANALYSIS':'METHODOLOGY'}</span><h3>{r.title}</h3><p>{r.cycle?'Cycle: '+periodLabel(r.cycle):'Reference product'}{r.meeting_date?' · Meeting: '+r.meeting_date:''}</p></div><a className="secondary" href={assetUrl(r.file)} target="_blank" rel="noreferrer" aria-label={'Open '+r.title}>View PDF <ArrowSquareOut/></a><a className="icon-button" href={assetUrl(r.file)} download aria-label={'Download '+r.title}><DownloadSimple/></a></article>)}{!reports.length&&<p className="empty-inline">No products match these filters.</p>}</div></section>
 <div className="analysis-two-column"><section className="analysis-card"><div className="card-heading"><div><h2>Data & county briefs</h2><p>{periodLabel(period)} · active evidence source and filters</p></div></div><div className="download-actions"><button className="secondary" onClick={onCSV}><DownloadSimple/>Download county data · CSV</button><button className="secondary" onClick={onBrief}><DownloadSimple/>{county?.name} brief · printable HTML</button></div><p className="small-note">Open the brief to print or save as PDF. Downloads exclude free-text notes and internal record IDs.</p></section><section className="analysis-card reliefweb-placeholder"><span className="report-type">RELIEFWEB</span><h2>Monthly final products on ReliefWeb</h2><p>A dedicated link for each monthly product will appear here when the publication URLs are supplied.</p><button className="secondary" disabled>ReliefWeb links coming soon</button><small>PDFs in the library above are available now.</small></section></div></main>;
}
export function Methodology({model,reference,onPeriod,onReset}){
 const [expanded,setExpanded]=useState(false);
 return <main className="analysis-page"><PageHeading eyebrow="METHODS & ACCOUNTABILITY" title="Understanding the evidence" text="What the scores mean, how the framework changed, and where each dataset comes from." action={<ResetButton onReset={onReset} title="Restore the default page view and collapse the methodology diagram."/>}/><div className="analysis-two-column"><section className="analysis-card"><h2>One data source: ActivityInfo</h2><p className="body-copy">All monthly maps, county indicators and analyses use the same ActivityInfo form. Manual data imports, annual HNRP figures and the fixed comparison study have been removed. Source values are not filled from another dataset. The PDF library contains reference documents only; their figures do not feed dashboard calculations.</p><p className="body-copy">This snapshot was fetched {new Date(model.fetchedAt).toLocaleDateString('en-GB',{dateStyle:'long'})}. Reporting months come directly from ActivityInfo; PDF analysis windows and meeting dates may differ.</p><div className="method-note">Current view: <b>{model.sourceLabel}</b>. Monthly data updates are manual and published as a static snapshot.</div></section><section className="analysis-card"><h2>Score, band, and adjustment</h2><p className="body-copy">Final needs severity scores range from 0 to 10. Bands are supplied classifications, not recalculated score buckets: IPC restrictions and meeting adjustments can affect the final result.</p><p className="body-copy">ActivityInfo labels are displayed unchanged. Earlier periods use A / B1 / B2 / C / D / E; revised periods use A–F. In severity order the earlier labels correspond to A / B / C / D / E / F, but we do not relabel source records or compare scores across the framework revision. The key below describes revised bands.</p><div className="band-definitions">{reference.bands.map(b=><span key={b.id}><i style={{background:b.color}}/><b>{b.id}</b> {b.label}</span>)}</div></section></div>
 <section className="analysis-card"><div className="card-heading"><div><h2>Framework revision · December 2025</h2><p>Climate and conflict were added; other pillar weights changed. Direct changes across the revision are withheld.</p></div></div><div className="table-scroll"><table><thead><tr><th>Indicator</th><th>Earlier maximum contribution</th><th>Revised maximum contribution</th></tr></thead><tbody>{reference.indicators.map(i=><tr key={i.id}><td>{i.name}</td><td>{i.max_v1||'Not included'}</td><td>{i.max_v2||'Not included'}</td></tr>)}</tbody></table></div><button className="text-button" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Hide':'View'} supplied methodology diagram <ArrowSquareOut/></button>{expanded&&<img className="framework-image" src={frameworkImage} alt="Supplied NAWG framework flowchart: vulnerability and trigger indicators leading to first-level and adjusted needs classification"/>}</section>
 <section className="analysis-card"><h2>Coverage & quality</h2><p className="body-copy">Means and medians use non-missing county scores with equal county weight, not population weighting. Comparisons use the same counties observed in both cycles. Persistent needs use observed-cycle denominators, with coverage alongside. Dotted county trend links are visual guides across gaps, not estimates.</p><p className="body-copy">{model.quality?.excludedInvalidDates||0} of {model.quality?.sourceRecords||model.rawCount} source rows have no valid year/month and are excluded from monthly analysis, not deleted in ActivityInfo. Conflicting ActivityInfo records are withheld from maps and aggregate scores; alternative submissions remain visible in county Indicator data. Free-text notes, record IDs and credentials are excluded from the public export.</p><p className="body-copy">Maps use OCHA COD county geometry and UN international boundary styles. Abyei is matched to the OCHA “Abyei Region” polygon. Boundaries, names and designations do not imply official UN endorsement or acceptance.</p><div className="table-scroll"><table><thead><tr><th>Cycle</th><th>Usable scores</th><th>Unresolved conflicts</th><th>View</th></tr></thead><tbody>{[...model.periods].reverse().map(p=><tr key={p}><td>{periodLabel(p)}</td><td>{model.coverage[p].valid} of {model.counties.length} counties</td><td>{model.coverage[p].conflicts}</td><td><button className="text-button" onClick={()=>onPeriod(p)}>Open cycle →</button></td></tr>)}</tbody></table></div></section></main>;
}
