import React from 'react';
import {isStatic,assetUrl} from './deployment.mjs';
import {DownloadSimple,FilePpt,FileCsv,FileText,Files,FilePdf,ArrowSquareOut} from '@phosphor-icons/react';
import {monthlyPublications} from './publications.mjs';
import {periodLabel} from './data-model.mjs';
import {downloadFile} from './Trend.jsx';
export function Publications({period,county,filtered,payload,onCSV,onBrief}) {
  return <main className="content-page"><span className="eyebrow">Knowledge & evidence</span><h1>Publications & downloads</h1><p className="page-intro">Meeting materials and source data, in one place.</p>{!isStatic&&<h2>Meeting publications</h2>}
    {!isStatic&&<div className="publication-row"><div className="publication-icon"><FilePpt size={28}/></div><div><h3>NAWG meeting · September 2026</h3><p>Original presentation supplied for this dashboard · PowerPoint</p><span className="document-tag">Meeting presentation</span></div><a className="secondary" href={assetUrl('publications/NAWG_September_2026.pptx')} download><DownloadSimple/>Download PPT</a></div>}
    <p className="publication-note">{isStatic?'This public release contains county indicators and downloadable county briefs. The original meeting presentation is not included.':'Presentation figures and dashboard figures may use different periods and classification schemes. Check the reporting period and source notes.'}</p>
    <section className="monthly-publications"><div className="monthly-publication-heading"><div><h2>Monthly final products</h2><p>Final PDFs and ReliefWeb pages · 2026</p></div><span className="pending-tag">Links coming soon</span></div><p className="publication-note">Month slots are shown below. PDF and ReliefWeb links will be added when provided; these placeholders do not indicate a published product.</p><div className="monthly-publication-grid">{monthlyPublications.map(item=><article key={item.period} className="monthly-publication-card"><FilePdf size={27}/><h3>{periodLabel(item.period,false)}</h3><span className="publication-link-status">{item.pdfUrl||item.reliefWebUrl?'Product links':'Awaiting links'}</span><div>{item.pdfUrl?<a className="secondary" href={item.pdfUrl} target="_blank" rel="noreferrer"><DownloadSimple/>PDF</a>:<button className="secondary" disabled title="PDF link has not been supplied"><DownloadSimple/>PDF</button>}{item.reliefWebUrl?<a className="secondary" href={item.reliefWebUrl} target="_blank" rel="noreferrer">ReliefWeb<ArrowSquareOut/></a>:<button className="secondary" disabled title="ReliefWeb link has not been supplied">ReliefWeb<ArrowSquareOut/></button>}</div></article>)}</div></section>
    <h2>Data & county briefs</h2><div className="publication-row"><div className="publication-icon"><FileCsv size={28}/></div><div><h3>Current-period county data</h3><p>{periodLabel(period,false)} · {filtered.length} counties in current filters · includes quality flags</p></div><button className="secondary" onClick={onCSV}><DownloadSimple/>Download CSV</button></div>
    <div className="publication-row"><div className="publication-icon"><FileText size={28}/></div><div><h3>{county?.name} county brief</h3><p>{periodLabel(period,false)} · printable HTML with scores, indicators and source notes</p></div><button className="secondary" onClick={onBrief}><DownloadSimple/>Download brief</button></div>
    <div className="publication-row"><div className="publication-icon"><Files size={28}/></div><div><h3>{isStatic?'Published county data':'ActivityInfo source extract'}</h3><p>{payload.rows.length.toLocaleString()} {isStatic?'county-level records · internal IDs and free-text notes excluded':'original records · includes duplicates and unmapped areas'}</p></div><button className="secondary" onClick={()=>downloadFile(isStatic?'NAWG-public-data.json':'NAWG-source-extract.json',JSON.stringify({source:payload.source,fetchedAt:payload.fetchedAt,rows:payload.rows},null,2),'application/json')}><DownloadSimple/>Download JSON</button></div></main>;
}
export function About({model,payload,onPeriod}) {
  return <main className="content-page about-page"><span className="eyebrow">Transparency by design</span><h1>Sources & methodology</h1><p className="page-intro">What is available, how it is shown, and where care is needed.</p><div className="about-grid">
    <section><h2>{isStatic?'Published evidence':'Connected evidence'}</h2><p>Read-only data from the supplied <a href="https://www.activityinfo.org/resources/query/v43/form/cdqmo0mmmapb33se" target="_blank" rel="noreferrer">ActivityInfo form</a>: {model.rawCount.toLocaleString()} records across {model.periods.length} reporting months, from {periodLabel(model.periods[0])} to {periodLabel(model.periods.at(-1))}.</p><p>Snapshot retrieved: {new Date(payload.fetchedAt).toLocaleString()}. {isStatic?'This is a static monthly release. The refresh control reloads the latest published snapshot; it does not query ActivityInfo. New months appear after the maintainer publishes an updated export. Internal identifiers and free-text notes are not included.':'The refresh control requests an updated extract and discovers newly uploaded months in the same form.'}</p><h3>Reporting periods are not update dates</h3><p>The initial view uses {periodLabel(model.defaultPeriod)}, the latest month with usable scores for at least 80% of mapped counties. Later partial periods remain selectable. Period menus show dates only; reporting coverage is explained beside the map and in the table below. The monthly timeline includes unreported months and shows them as missing, never as zero severity.</p><h3>Source bands</h3><p>Band categories are displayed exactly as reported for the selected period. Historical A/B1/B2/C/D categories are not converted to A–F. New categories appear when uploaded to the form. No conversion or score thresholds are invented.</p></section>
    <section><h2>Data treatment</h2><p>Edited score and band fields take precedence when supplied. Original fields are retained in downloads. Source indicator classifications are displayed without recalculating them.</p><p>{model.duplicates.length} county/month groups contain multiple records; {model.duplicates.filter(d=>d.conflict).length} have conflicting metric values. Conflicting groups have no displayed score or band. Identical metric duplicates are collapsed for display.</p><p>{model.unmapped.length} records have no matching county polygon; {model.invalid.length} have invalid reporting dates. All remain in the source export. Missing observations remain unavailable, not zero. Dotted chart links span gaps between reported values; they are not estimates.</p><h3>Map boundaries</h3><p><a href="https://gis.unocha.org/server/rest/services/COD/GLB_COD_Admin2/MapServer/0" target="_blank" rel="noreferrer">OCHA Common Operational Datasets</a> · {model.counties.length} polygons. Names join after case and punctuation normalization. The explicit name alias “Abyei Administrative Area” maps to “Abyei Region” (SS0001).</p><p><a href="https://gis.unocha.org/server/rest/services/Hosted/World_International_Boundaries__Adm0___Line/FeatureServer/0" target="_blank" rel="noreferrer">UN international boundary lines</a> separate neighboring countries. Solid, dashed and dotted styles retain the source distinctions: international boundaries; armistice, undetermined or international administrative lines; and other lines of separation. The two geographic sources may differ slightly in detail.</p><p>Boundaries and names shown do not imply official endorsement or acceptance by the United Nations.</p></section>
    </div><section className="coverage-table-section"><h2>Reporting coverage</h2><table><thead><tr><th>Period</th><th>Usable scores</th><th>Reported counties</th><th>Conflicts</th><th>Mapped counties</th></tr></thead><tbody>{[...model.periods].reverse().map(p=><tr key={p}><td><button className="text-button" onClick={()=>onPeriod(p)}>{periodLabel(p)}</button></td><td>{model.coverage[p].valid}</td><td>{model.coverage[p].reported}</td><td>{model.coverage[p].conflicts}</td><td>{model.counties.length}</td></tr>)}</tbody></table></section></main>;
}
